# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7f8010f97a5afba4b80c7c1073789095d0521d5d96a809ac4ba17269718288c137ef1d9c063542c73e64bc256d1b6e8380299d45f868389e14b7719c055da46
  twitter_api_key: <%= ENV['TWITTER_API_KEY'] %>
  twitter_api_secret: <%= ENV['TWITTER_API_SECRET'] %>
  github_app_id: <%= ENV['GITHUB_CLIENT_ID'] %>
  github_app_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>

test:
  secret_key_base: 690aa7e20725490fd9e93acb66cebe44205754c10cba2dbe1c5f8dc10d029a7179dc9e30bb2b92b39ab97770cf33ce15358233e405b90139d3a3463287fd9670
  twitter_api_key: abc123
  twitter_api_secret: def456
  github_app_id: abc123
  github_app_secret: def456
  facebook_app_id: abc123
  facebook_app_secret: def456

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 690aa7e20725490fd9e93acb66cebe44205754c10cba2dbe1c5f8dc10d029a7179dc9e30bb2b92b39ab97770cf33ce15358233e405b90139d3a3463287fd9670
  twitter_api_key: <%= ENV['TWITTER_API_KEY'] %>
  twitter_api_secret: <%= ENV['TWITTER_API_SECRET'] %>
  github_app_id: <%= ENV['GITHUB_CLIENT_ID'] %>
  github_app_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
